import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../../services/api";
import "../../styles/dashboard.css";
const emptyForm={name:"",code:"",description:"",academic_year:""};
function Classes(){const navigate=useNavigate();const[classes,setClasses]=useState([]),[form,setForm]=useState(emptyForm),[editingId,setEditingId]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
const loadClasses=async()=>{try{setLoading(true);setError("");const r=await api.get("/classes");setClasses(r.data)}catch(e){setError(e.response?.data?.message||"Unable to load classes.")}finally{setLoading(false)}};useEffect(()=>{loadClasses()},[]);const handleChange=e=>setForm(c=>({...c,[e.target.name]:e.target.value}));const reset=()=>{setForm(emptyForm);setEditingId(null)};
const submit=async e=>{e.preventDefault();try{setSaving(true);setError("");if(editingId){const r=await api.put(`/classes/${editingId}`,form);setClasses(c=>c.map(x=>x.id===editingId?{...x,...r.data}:x))}else{const r=await api.post("/classes",form);setClasses(c=>[...c,r.data].sort((a,b)=>a.name.localeCompare(b.name)))}reset()}catch(e){setError(e.response?.data?.message||"Unable to save class.")}finally{setSaving(false)}};
const edit=x=>{setEditingId(x.id);setForm({name:x.name,code:x.code,description:x.description||"",academic_year:x.academic_year||""});window.scrollTo({top:0,behavior:"smooth"})};const del=async id=>{if(!window.confirm("Delete this class?"))return;try{await api.delete(`/classes/${id}`);setClasses(c=>c.filter(x=>x.id!==id))}catch(e){setError(e.response?.data?.message||"Unable to delete class.")}};
return <div className="dashboard-page classes-page"><div className="page-header"><div><span className="eyebrow">VLE CLASS MANAGEMENT</span><h1>Classes</h1><p>Create real learning spaces that connect students, teachers and subjects.</p></div><div className="stat-card"><strong>{classes.length}</strong><span>Learning Spaces</span></div></div>{error&&<div className="error-message">{error}</div>}
<section className="dashboard-card class-form-card"><div className="card-heading"><div><h2>{editingId?"Edit Class":"Create a Class"}</h2><p>{editingId?"Update the class details.":"Every class becomes a functional VLE space."}</p></div>{editingId&&<button type="button" className="secondary-button" onClick={reset}>Cancel</button>}</div><form onSubmit={submit} className="class-form-grid"><label>Class name<input name="name" placeholder="e.g. JHS 1" value={form.name} onChange={handleChange} required/></label><label>Class code<input name="code" placeholder="e.g. JHS1" value={form.code} onChange={handleChange} required/></label><label>Academic year<input name="academic_year" placeholder="e.g. 2026/2027" value={form.academic_year} onChange={handleChange}/></label><label className="wide-field">Description<textarea name="description" rows="3" placeholder="What will this class learn?" value={form.description} onChange={handleChange}/></label><button type="submit" disabled={saving}>{saving?"Saving...":editingId?"Save Changes":"+ Create Class"}</button></form></section>
<section className="dashboard-card"><div className="card-heading"><div><h2>Your Learning Spaces</h2><p>Open a class to manage its connected VLE community.</p></div></div>{loading?<div className="empty-state">Loading classes...</div>:!classes.length?<div className="empty-state"><strong>No classes yet</strong><span>Create your first learning space above.</span></div>:<div className="class-grid">{classes.map(x=><article className="class-card class-space-card" key={x.id} onClick={()=>navigate(`/organization/classes/${x.id}`)}><div className="class-card-top"><span className="class-code">{x.code}</span><span>{x.academic_year||"No year set"}</span></div><h3>{x.name}</h3><p>{x.description||"Open this learning space to connect your VLE community."}</p><div className="class-metrics"><span>👨‍🎓 {x.student_count||0} Students</span><span>👨‍🏫 {x.teacher_count||0} Teachers</span><span>📚 {x.subject_count||0} Subjects</span></div><div className="class-actions" onClick={e=>e.stopPropagation()}><button type="button" onClick={()=>navigate(`/organization/classes/${x.id}`)}>Open Class</button><button type="button" onClick={()=>edit(x)}>Edit</button><button type="button" className="danger-button" onClick={()=>del(x.id)}>Delete</button></div></article>)}</div>}</section></div>}
export default Classes;
