import { useEffect,useState } from "react";
import api from "../../services/api";
import "../../styles/dashboard.css";
const emptyForm={full_name:"",email:"",phone:"",gender:"",date_of_birth:"",class_name:"",password:""};
function Students(){const[students,setStudents]=useState([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[form,setForm]=useState(emptyForm);
const loadStudents=async()=>{try{setLoading(true);setError("");const r=await api.get("/students");setStudents(r.data)}catch(e){setError(e.response?.data?.message||"Unable to load students.")}finally{setLoading(false)}};useEffect(()=>{loadStudents()},[]);const handleChange=e=>setForm({...form,[e.target.name]:e.target.value});const handleSubmit=async e=>{e.preventDefault();try{setSaving(true);setError("");await api.post("/students",form);setForm(emptyForm);await loadStudents()}catch(err){setError(err.response?.data?.message||"Unable to add student.")}finally{setSaving(false)}};const handleDelete=async id=>{if(!window.confirm("Delete this student?"))return;try{setError("");await api.delete(`/students/${id}`);setStudents(c=>c.filter(s=>s.id!==id))}catch(e){setError(e.response?.data?.message||"Unable to delete student.")}};
return <div className="dashboard-page people-page"><div className="page-header"><div><span className="eyebrow">LEARNER DIRECTORY</span><h1>Student Management</h1><p>Organize your learners and keep their academic records easy to manage.</p></div><div className="stat-card student-stat"><strong>{students.length}</strong><span>Registered Students</span></div></div>{error&&<div className="error-message">{error}</div>}
<section className="dashboard-card people-form-card student-form-card"><div className="card-heading"><div><h2>Add a Student</h2><p>Create a learner profile and assign their class.</p></div><span className="section-accent green">Learners</span></div><form onSubmit={handleSubmit} className="class-form-grid"><label>Full name<input name="full_name" placeholder="e.g. Kofi Mensah" value={form.full_name} onChange={handleChange} required/></label><label>Email address<input name="email" type="email" placeholder="student@example.com" value={form.email} onChange={handleChange} required/></label><label>Phone<input name="phone" placeholder="Phone number" value={form.phone} onChange={handleChange}/></label><label>Gender<select name="gender" value={form.gender} onChange={handleChange}><option value="">Select gender</option><option value="Male">Male</option><option value="Female">Female</option></select></label><label>Date of birth<input name="date_of_birth" type="date" value={form.date_of_birth} onChange={handleChange}/></label><label>Class<input name="class_name" placeholder="e.g. JHS 1" value={form.class_name} onChange={handleChange}/></label><label>Temporary password<input name="password" type="password" placeholder="Create temporary password" value={form.password} onChange={handleChange} required/></label><div className="form-action"><button type="submit" disabled={saving}>{saving?"Creating...":"+ Add Student"}</button></div></form></section>
<section className="dashboard-card"><div className="card-heading"><div><h2>Student Directory</h2><p>Registered learners in your organization.</p></div></div>{loading?<div className="empty-state">Loading student directory...</div>:students.length===0?<div className="empty-state"><strong>No students yet</strong><span>Add your first learner above.</span></div>:<div className="people-grid">{students.map(s=><article className="person-card student-card" key={s.id}><div className="person-avatar student-avatar">{s.full_name?.charAt(0)?.toUpperCase()}</div><div className="person-info"><span className="person-id">{s.student_id}</span><h3>{s.full_name}</h3><p>{s.class_name||"Class not assigned"}</p><small>{s.email}</small>{s.phone&&<small>{s.phone}</small>}</div><button className="person-delete" type="button" onClick={()=>handleDelete(s.id)}>Remove</button></article>)}</div>}</section></div>}
export default Students;
